---
rvm:
  - 1.9.3
  - 2.0.0
deploy:
  provider: heroku
  api_key:
    secure: "Xy/0H+q2q9O9J5+VRrVJDmbRBUEuhb5VeYaiJgvQVsmAMuctvMCdkWs95qyY\nyCtWu01cQ1vYIz8DXG2aDl3jyekjiSU0XihLCVt05M6U657qSz4odHqSkfQQ\n8Haul5wGkdMDTI/6pMI+Ci6EgaBLF5m65W4RUEb71ARyYqyUNGY="
  on:
    rvm: 2.0.0
  run: "rake hello"
